disabled_rules:
 - trailing_whitespace
 - unused_closure_parameter
 - identifier_name
excluded: # 執行 linting 時忽略的路徑。 優先順序比 included 更高。
 - Pods
 - Carthage
min_length: # only min_length
  error: 4 # only error

